=== nmala001/Handson_SOAP/PatientXML/Insurer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.nandithmalapati.com/Insurer"
	xmlns:tns="http://www.nandithmalapati.com/Insurer"
	elementFormDefault="qualified">
	
	<element name="insurer" type= "tns:Insurer"/>
	
		<complexType name="Insurer">
			<sequence>
				<element name="id" type= "int"/>
				<element name="name" type= "string"/>
				<element name="age" type= "int"/>
				<element name="dob" type= "date"/>
				<element name="email" type= "string"/>
				<element name="gender" type= "string"/>
				<element name="phone" type= "string"/>
			</sequence>
		</complexType>
</schema>

=== nmala001/Handson_SOAP/PatientXML/Insurer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:insurer
	xmlns:tns="http://www.nandithmalapati.com/Insurer"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nandithmalapati.com/Insurer Insurer.xsd ">
	<tns:id>1</tns:id>
	<tns:name>Nandith</tns:name>
	<tns:age>27</tns:age>
	<tns:dob>2001-01-01</tns:dob>
	<tns:email>nandith.malapati@gmail.com</tns:email>
	<tns:gender>male</tns:gender>
	<tns:phone>1234567890</tns:phone>
</tns:insurer>
